sudo: required
dist: trusty
script:
    - sudo apt-get update
    - sudo apt-get -y install lintian
    - sudo make install-deb
    - scripts/update_lintian
    - lintian --profile debian -i -EvIL +pedantic ../vimpager*.changes
