sudo: required
dist: trusty
install:
    - sudo make install-deb
    - scripts/update_lintian
    - sudo apt-get install bats
script:
    - lintian --profile debian -i --fail-on-warnings -EvIL +pedantic ../vimpager*.changes
    - make test
